###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=magento
            - MYSQL_USER=user
            - MYSQL_PASSWORD=123
        ports:
            - '8002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './{nome_da_pasta_magento}:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './phpdocker/nginx/magento.conf:/etc/nginx/magento.conf'
        ports:
            - '8000:80'
            
    elasticsearch:
        image: 'elasticsearch:7.17.6'
        environment:
            - 'discovery.type=single-node'
            - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
        ports:
            - '9200:9200'
            - '9300:9300'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        container_name: mgphp
        volumes:
            - './{nome_da_pasta_magento}:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
